### ISSUE TITLE
Code explanation request

### ISSUE THREAD

**Issue by woodpk** [AfterLutz/Akkatecture#114]
This may be a big ask (you could consider me to be --less than-- a junior developer), but can anyone help me understand by explaining the code for the InitReceives() method in the DomainEventSubscriber base class?

It looks like maybe the method is converting the derived class Handle methods into Receive methods of the DomainEventSubscriber's base ReceiveActor class.  I'm guessing its just using a lot of reflection to extract the method info from the Handle method and magic that method info into a Receive method.... but i'm not totally sure.  The last foreach loops is confusing to me (because i don't really yet know anything about reflection), but i'm guessing that is the final conversation and creation step to actually make the final Receive methods ?

**Comment by malclear** [comment]
Hi @woodpk, 
It's my pleasure. 

You are correct: `InitReceives` does use reflection to programmatically call the `DomainEventSubscriber`'s Receive functions. The `Receive` method is, of course, a function in Akka's `ReceiveActor` base class. Here, Akkatecture is using the power of convention to make development simpler at design time.

1) In the `InitReceives` method, a collection of `System.Type` instances is gathered. This collection is all of the DomainEvent types to which the actor has a subscription. It gets this list using the `GetDomainEventSubscriberSubscriptionTypes` extension method (described below). 
2) Next, an instance of `MethodInfo` is created that represents the generic `Receive<T>(Func<T, bool> handler)` function of the base class and is stored in `method`.
3) Each time through the foreach loop of subscription types, a `MethodInfo` instance representing an instance of `Receive` is created, where that method's generic parameters are closed over. In other words, instead of an open generic method such as...
```
Receive<T>(Func<T, bool> handler);
```
... the instance would be *closed* like this:
```
Receive<MyEvent>(Func<MyEvent, bool> handler);
```
4) Finally, the closed method is invoked passing in the subscriber's corresponding `methodInfo` gathered in step 1.

With all of this code in the library, a developer only needs to extend the `DomainEventSubscriber` class and add however many `ISubscribeTo<,,>` interfaces they want. For each subscription interface/type, they would create a `Handle` method with the related type as the only parameter.

 [Example here](https://github.com/AfterLutz/Akkatecture/blob/dev/test/Akkatecture.TestHelpers/Subscribers/TestAggregateSubscriber.cs)

*********

##### GetDomainEventSubscriberSubscriptionTypes
A parameterless extension method of the Type class, it...
- Filters the interfaces extended by the type in question to those that are implementations of  `ISubscribeTo<,,>`
- Selects the third of the three generic types specified in that `ISubscribeTo`  implementation: the `IDomainEvent<,,>`
- Returns the complete list of domain event types.
