### ISSUE TITLE
Behavior switching w/ Become() w/in the context of a DomainEventSubscriber

### ISSUE THREAD

**Issue by woodpk** [AfterLutz/Akkatecture#115]
I am trying to build a draft form of a durable projection system for Akkatecture. I am wanting to use some of the concept of how the DomainEventSubscriber was built to do this.  However, I would also like to be able to implement behavior switching (to enable a projector manager to 'play', 'pause' , 'stop' projectors and possibly other administrative functions.  

Would it be possible to implement behavior switching with the way that the DomainEventSubscriber creates the Receive<> methods ?  That is, I know that each Behavior (private void SomeBehavior() method ) has to have its own set of Receive<> methods to describe its behavior.  How would I go about populating the Behavior methods with the Receive<> methods they need ?  Would a call to a reflection based "CreateHandlers" method be needed at the top of each Behavior method be required ?  For example, something like this ?

```
        private void Playing()
        {
            CreateHandlers();

            Command<PauseReactorCmd>(cmd =>
            {
                Become(Paused);
                Context.Parent.Tell(new PauseReactorAck());

            });

            Command<SomeOtherMsg>(cmd => {}); ...

        }
```

**Comment by malclear** [comment]
This is an interesting idea. I'd like to learn more what you hope to accomplish with that functionality.

I think it would not be necessary to use reflection to add more methods. The reflection in use by the library allows developers to denote their custom Event types and then have Receive methods invoked on them. You could write your own boilerplate functions in a new child class of DomainEventSubscriber. It would still operate as DomainEventSubscriber does now, but then you'd also have the state machine-related functions you want there too.

I will say that the resumeable projections I've created, I ran in an entirely different process. It used a "shallow", read-only Actor System in order to query the Event Journal via Akka.Persistence.Query. I did not use event subscribers for this purpose, though I know it's possible.

**Comment by malclear** [comment]
Reach out if you have more thoughts on this.
